version: '3'

tasks:
  default:
     deps: [test]
  
  build:
    deps: [format, vet]
    cmds:
      - go build -v

  test:
    deps: [build]
    cmds:
      - go test -v ./...

  format:
    cmds:
      - go fmt
  vet:
    cmds:
      - go vet

  mod:
    cmds:
      - go mod download
      - go mod tidy
